Users/pool supervision tree
esl/amoc pull request #175
Opened 2023-12-16 14:13 UTC by NelsonVides

If users go up and down too fast, amoc_users_sup becomes a bottleneck as it
can’t keep up with the requests. Improve the performance by creating a pool of
supervisors whose size is proportional to the number of schedulers, and ensure
distribution of users among them by for example hashing on the user_id.

We do this by creating a pool of supervisors and having the whole API through
`amoc_users_sup_sup` choose supervisors according to requests.

2024-02-18 00:54 UTC, DenysGonchar requested changes
this new implementation sufferrs from the same issues as the existing one. removal operation is async and if we call `amoc_controller:remove_users/2` two times in a row, it may select the same users for removal. so it won't remove the expected amount of users (the number returned by `amoc_controller:remove_users/2`). I don't think that we need to worry about it, but we must to add a note in the documentation about this behaviour.

2024-02-18 00:54 UTC, DenysGonchar commented on src/users/amoc_users_worker_sup.erl
> +    Tid = ets:new(?MODULE,  [ordered_set, private]),
any particular reason to make it private? why not protected and not named?
these settings make troubleshooting much harder.

2024-02-18 00:54 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +    gen_server:cast(Sup, {start_child, Scenario, Id, ScenarioState}).
never expose details of internal `gen_server` protocol, create interface at `amoc_users_worker_sup` module and call it instead.

2024-02-18 00:54 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +                      gen_server:cast(Sup, {start_children, Scenario, Users, ScenarioState})
never expose details of internal `gen_server` protocol, create interface at `amoc_users_worker_sup` module and call it instead.

2024-02-18 00:54 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +    [ gen_server:cast(Sup, {stop_children, Int, Force}) || {Sup, Int} <- Assignments ],
never expose details of internal `gen_server` protocol, create interface at `amoc_users_worker_sup` module and call it instead.

2024-02-18 00:54 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +    All = [ gen_server:call(Sup, get_all_children, infinity) || Sup <- tuple_to_list(Sups) ],
never expose details of internal `gen_server` protocol, create interface at `amoc_users_worker_sup` module and call it instead.

2024-02-18 00:54 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +    [ gen_server:cast(Sup, terminate_all_children) || Sup <- tuple_to_list(Sups) ].
never expose details of internal `gen_server` protocol, create interface at `amoc_users_worker_sup` module and call it instead.

2024-02-18 00:54 UTC, DenysGonchar commented on src/users/amoc_users_worker_sup.erl
> +    case amoc_user:start_link(Scenario, Id, ScenarioState) of
please move this logic into a `start_child` function and reuse it for `start_children` processing

2024-02-20 19:13 UTC, NelsonVides commented on src/users/amoc_users_sup.erl
> +init_storage() ->
The supervisor docs say that
> Notice that this function can also be called as a part of a code upgrade procedure. Therefore, the function is not to have any side effects. For more information about code upgrade of supervisors, see section [Changing a Supervisor](https://www.erlang.org/doc/design_principles/appup_cookbook#sup) in OTP Design Principles.

That's why I chose to put it aside. However we might actually never consider upgrades a thing for a load-test though 😄

2024-02-20 19:17 UTC, NelsonVides commented on src/users/amoc_users_sup.erl
> +init_storage() ->
Oh, also, the other issue is that the supervisor hasn't started its children, so we don't know yet the pids to store in a pt.

2024-02-20 19:54 UTC, NelsonVides commented on src/amoc_controller.erl
> +    State#state{create_users = [], tref = maybe_stop_timer(TRef)}.
Yeah, I'm already calling it precisely 😄

2024-02-20 19:57 UTC, NelsonVides commented on src/users/amoc_users_sup.erl
> +    atomics:sub(Atomics, SupNum + 1, 1),
Yeah I know, but I'm not using the result on this operation, this is just subtracting one on the index of the supervisor, it is the operation just below the one that checks if it is the total index the one being counted.

2024-02-20 20:40 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +init_storage() ->
`start_link/0` calls `supervisor:start_link/3` and `supervisor:start_link/3` returns only after sup. tree initialization is done. so by the time of returning from that function all the workers are initialized and we can grab the pids.

2024-02-20 20:41 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +clean_storage() ->
we don't really care about cleaning, because the value must be reset on init anyway.

2024-02-20 20:47 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +    atomics:sub(Atomics, SupNum + 1, 1),
right, the index... haven't noticed that

2024-02-20 21:03 UTC, NelsonVides commented on src/users/amoc_users_sup.erl
> +init_storage() ->
Aaaaah that's what you mean, ok, thought you were referring to the `init` callback. Cool 👌🏽

2024-02-20 22:09 UTC, DenysGonchar commented on src/amoc_controller.erl
> +-spec terminate(term(), state()) -> any().
terminate is an optional callback, it can be removed

2024-02-21 18:10 UTC, DenysGonchar commented on test/controller_SUITE.erl
> +total_count_is_the_exact_sum_of_the_values_in_the_input(_) ->
in the output

2024-02-21 18:13 UTC, DenysGonchar commented on test/controller_SUITE.erl
> +     {distribute, [parallel], distribute()},
please add one more test:
* The number of items in the resulting KV list is equal to the number of non-zero items in the input KV list or requested amount (equal to the lower number)

2024-02-21 18:17 UTC, DenysGonchar commented on test/controller_SUITE.erl
> +                  Count =:= Total orelse Count =:= Assinged
`Count =:= Assinged` is another property checked in the following TC, it should be like this:

```
Available = lists:sum([ N || {_, N} <- SupervisorWithCounts ]),
Count =:= min(Total, Available)
```

2024-02-21 18:18 UTC, DenysGonchar commented on test/controller_SUITE.erl
> +total_count_is_always_less_than_or_equal_the_requested_amount(_) ->
we can get rid of this TC if we check `Count =:= min(Total, Available)` in the following TC.

2024-02-21 18:35 UTC, DenysGonchar commented on src/users/amoc_users_worker_sup.erl
> +    Tid = ets:new(?MODULE,  [ordered_set, protected]),
please make it named `list_to_atom(atom_to_list(__MODULE__) ++ integer_to_list(tid))`
so it's easy to identify the table.

2024-02-21 19:12 UTC, DenysGonchar commented on src/users/amoc_users_sup.erl
> +    UserSups = lists:reverse(supervisor:which_children(?MODULE)),
please rewrite it in this way:
```
UserSups = supervisor:which_children(?MODULE),
IndexedSupsUnsorted = [ {Pid, N} || {{amoc_users_worker_sup, N}, Pid, _, _} <- UserSups],
IndexedSups = lists:keysort(2, IndexedSupsUnsorted),
UserSupPidsTuple = list_to_tuple([ Pid || {Pid, _} <- IndexedSups ]),
SupCount = tuple_size(UserSupPidsTuple),
Atomics = atomics:new(1 + SupCount, [{signed, false}]),
Storage = #storage{user_count = Atomics, sups = UserSupPidsTuple,
                   sups_indexed = IndexedSups, sups_count = SupCount},
persistent_term:put(?MODULE, Storage),
Ret.```

2024-02-21 22:11 UTC, DenysGonchar approved these changes
thanks for the huge amount of work, it looks really greate :)

2024-02-21 22:14 UTC, merged